// ImportRetrofitCSV.cs
// ✅ Keep your original big logic (CSV -> write -> DeepSeek once -> write -> report -> export -> popup)
// ✅ Add requested changes:
//   - ea_wall_u_value / ea_roof_u_value / ea_slab_u_value / ea_orientation_deg: read from Revit (not CSV) and write back (instance OR type)
//   - lt_vlt / lt_glare_risk_class: generated by AI and written to Windows (instance OR type)
// ✅ Fix angle internal unit for *_deg (degrees -> internal radians)

using Autodesk.Revit.DB;
using Autodesk.Revit.UI;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using Newtonsoft.Json;

namespace RevitLOD3Exporter
{
    [Autodesk.Revit.Attributes.Transaction(Autodesk.Revit.Attributes.TransactionMode.Manual)]
    public class ImportRetrofitCSV : IExternalCommand
    {
        private const string DEEPSEEK_MODEL = "deepseek-chat";
        private const string REPORT_PARAM_NAME = "leed_retrofit_report";
        private const bool EXPORT_REPORT_TXT = true;

        private static readonly string[] GLOBAL_PARAMS = new[]
        {
            "building_id",
            "retrofit_score_total",
            "ea_score",
            "ss_score",
            "we_score",
            "lt_score",
            "lt_daylight_potential",
            "ss_heat_island",
        };

        // CSV forced into windows
        private static readonly string[] WINDOW_CSV_FORCE_PARAMS = new[]
        {
            "ea_window_u_value"
        };

        // ✅ NEW: these are NOT from CSV anymore; we will compute/read from Revit and write back
        private static readonly string[] REVIT_DERIVED_PARAMS = new[]
        {
            "ea_wall_u_value",
            "ea_roof_u_value",
            "ea_slab_u_value",
            "ea_orientation_deg"
        };

        public Result Execute(ExternalCommandData commandData, ref string message, ElementSet elements)
        {
            try
            {
                UIApplication uiapp = commandData.Application;
                UIDocument uidoc = uiapp.ActiveUIDocument;
                Document doc = uidoc.Document;

                // 1) Select CSV
                string csvPath = SelectCSVFile();
                if (string.IsNullOrEmpty(csvPath))
                {
                    TaskDialog.Show("Cancelled", "CSV import cancelled.");
                    return Result.Cancelled;
                }

                // ✅ User selects output folder for report txt
                string reportOutDir = null;
                if (EXPORT_REPORT_TXT)
                {
                    reportOutDir = SelectReportOutputFolder();
                }

                // ✅ Determine forced building_id FIRST
                string forcedBuildingId = GetForcedBuildingIdFromFileName(csvPath);

                // 2) Read CSV (header + matching row by building_id; fallback to first non-empty row)
                var rowDict = ReadMatchingRowAsDict(csvPath, forcedBuildingId);
                if (rowDict == null || rowDict.Count == 0)
                {
                    TaskDialog.Show("CSV Error", "CSV is empty or invalid, or matching building_id row not found.");
                    return Result.Failed;
                }

                if (!string.IsNullOrWhiteSpace(forcedBuildingId))
                    rowDict["building_id"] = forcedBuildingId;

                // 3) Collect elements
                var roofs = new FilteredElementCollector(doc)
                    .OfCategory(BuiltInCategory.OST_Roofs)
                    .WhereElementIsNotElementType()
                    .ToElements();

                var windows = new FilteredElementCollector(doc)
                    .OfCategory(BuiltInCategory.OST_Windows)
                    .WhereElementIsNotElementType()
                    .OfType<FamilyInstance>()
                    .Cast<Element>()
                    .ToList();

                var walls = new FilteredElementCollector(doc)
                    .OfCategory(BuiltInCategory.OST_Walls)
                    .WhereElementIsNotElementType()
                    .OfType<Wall>()
                    .Cast<Element>()
                    .ToList();

                var floors = new FilteredElementCollector(doc)
                    .OfCategory(BuiltInCategory.OST_Floors)
                    .WhereElementIsNotElementType()
                    .ToElements();

                // ✅ Collect ALL Views, excluding templates
                var views = new FilteredElementCollector(doc)
                    .OfClass(typeof(Autodesk.Revit.DB.View))
                    .Cast<Autodesk.Revit.DB.View>()
                    .Where(v => v != null && !v.IsTemplate)
                    .ToList();

                int csvRoof = 0, csvWindow = 0, csvWall = 0, csvFloor = 0, csvProj = 0, csvView = 0;
                int apiRoof = 0, apiWindow = 0, apiWall = 0, apiFloor = 0, apiProj = 0;

                int wwrWallWrites = 0;
                int wwrWinWrites = 0;
                int ensuredRoofWrites = 0;

                // ✅ NEW counters for Revit-derived writebacks
                int revitWallU = 0, revitRoofU = 0, revitSlabU = 0, revitOri = 0;

                LeedPlan leedPlan = null;
                string aiRaw = "";
                string reportText = "";
                bool apiOk = false;

                // 4) Call AI once (LEED plan)
                try
                {
                    leedPlan = CallDeepSeekLeedPlan(rowDict, out aiRaw);
                    apiOk = (leedPlan != null);
                    reportText = BuildHumanReportText(leedPlan, rowDict);
                }
                catch (Exception ex)
                {
                    aiRaw = ex.ToString();
                    reportText = "LEED plan generation failed.\n\n" + aiRaw;
                    apiOk = false;
                }

                ShowTimedPopup(
                    "DeepSeek API Status",
                    apiOk ? "✅ DeepSeek API call successful: LEED Plan generated."
                          : "❌ DeepSeek API call failed: LEED Plan not generated.",
                    5
                );

                using (Transaction tx = new Transaction(doc, "CSV + LEED Retrofit Import"))
                {
                    tx.Start();

                    // =====================================================
                    // 5) CSV → write all matching parameters (your original logic)
                    // =====================================================
                    foreach (var r in roofs) csvRoof += WriteAllCsvParams(doc, r, rowDict);

                    foreach (var w in windows)
                    {
                        csvWindow += WriteAllCsvParams(doc, w, rowDict);
                        csvWindow += WriteWindowCsvForced(doc, w, rowDict);
                    }

                    foreach (var wa in walls) csvWall += WriteAllCsvParams(doc, wa, rowDict);
                    foreach (var f in floors) csvFloor += WriteAllCsvParams(doc, f, rowDict);

                    // ✅ write CSV global params into ProjectInformation and Views
                    csvProj += WriteCsvParamsByName(doc, doc.ProjectInformation, rowDict, GLOBAL_PARAMS);
                    foreach (var v in views)
                        csvView += WriteCsvParamsByName(doc, v, rowDict, GLOBAL_PARAMS);

                    // ✅ HARD ENSURE: ss_heat_island + lt_daylight_potential into ProjectInfo + Views (instance OR type)
                    EnsureWriteCsvExact(doc, doc.ProjectInformation, rowDict, "ss_heat_island");
                    EnsureWriteCsvExact(doc, doc.ProjectInformation, rowDict, "lt_daylight_potential");
                    foreach (var v in views)
                    {
                        EnsureWriteCsvExact(doc, v, rowDict, "ss_heat_island");
                        EnsureWriteCsvExact(doc, v, rowDict, "lt_daylight_potential");
                    }

                    // =====================================================
                    // ✅ NEW (A): Revit-derived parameters (NOT from CSV)
                    //   - Wall/Roof/Floor U-values: try read from type by common parameter names (U-Value/U-Wert etc.)
                    //   - Orientation for exterior walls: compute azimuth deg and write to wall + its hosted windows
                    // =====================================================

                    // A1) Wall U-value -> write to each wall (instance OR type). If missing, write 0.
                    foreach (var e in walls)
                    {
                        var wall = e as Wall;
                        if (wall == null) continue;

                        double uWall = 0.0; // default = 0
                        if (TryGetUValueFromElementType(doc, wall, out double foundU) && !double.IsNaN(foundU) && foundU >= 0)
                            uWall = foundU;

                        if (EnsureSetDoubleInstanceOrType(doc, wall, "ea_wall_u_value", uWall))
                            revitWallU++;
                    }

                    // A2) Roof U-value -> write to each roof (instance OR type). If missing, write 0.
                    foreach (var r in roofs)
                    {
                        double uRoof = 0.0; // default = 0
                        if (TryGetUValueFromElementType(doc, r, out double foundU) && !double.IsNaN(foundU) && foundU >= 0)
                            uRoof = foundU;

                        if (EnsureSetDoubleInstanceOrType(doc, r, "ea_roof_u_value", uRoof))
                            revitRoofU++;
                    }

                    // A3) Slab/Floor U-value -> write to each floor (instance OR type). If missing, write 0.
                    foreach (var f in floors)
                    {
                        double uSlab = 0.0; // default = 0
                        if (TryGetUValueFromElementType(doc, f, out double foundU) && !double.IsNaN(foundU) && foundU >= 0)
                            uSlab = foundU;

                        if (EnsureSetDoubleInstanceOrType(doc, f, "ea_slab_u_value", uSlab))
                            revitSlabU++;
                    }

                    // A4) Orientation degrees for EXTERIOR walls -> write to wall + its hosted windows
                    var wallWinMap = BuildWallToWindowsMap(doc, windows);
                    foreach (var e in walls)
                    {
                        var wall = e as Wall;
                        if (wall == null) continue;
                        if (!IsExteriorWall(wall)) continue;

                        if (!TryGetWallAzimuthDeg(wall, out double azDeg)) continue;

                        // write to wall
                        if (EnsureSetDoubleInstanceOrType(doc, wall, "ea_orientation_deg", azDeg))
                            revitOri++;

                        // also write to hosted windows if any
                        if (wallWinMap.TryGetValue(wall.Id, out var winsOnWall) && winsOnWall != null)
                        {
                            foreach (var w in winsOnWall)
                                EnsureSetDoubleInstanceOrType(doc, w, "ea_orientation_deg", azDeg);
                        }
                    }

                    // =====================================================
                    // 6) API → write generated parameters (your original)
                    // =====================================================
                    if (leedPlan != null)
                    {
                        foreach (var r in roofs) apiRoof += WriteApiToRoof(doc, r, leedPlan);
                        foreach (var w in windows) apiWindow += WriteApiToWindow(doc, w, leedPlan);
                        foreach (var wa in walls) apiWall += WriteApiToWall(doc, wa, leedPlan);
                        foreach (var f in floors) apiFloor += WriteApiToFloor(doc, f, leedPlan);
                        apiProj += WriteApiToProjectInfo(doc, leedPlan);
                    }

                    // =====================================================
                    // ✅ FIX A: we_roof_rainwater_strategy MUST write into Dächer
                    // =====================================================
                    string weRoofRain = leedPlan?.we?.strategies?.we_roof_rainwater_strategy ?? "";
                    if (!string.IsNullOrWhiteSpace(weRoofRain))
                    {
                        foreach (var r in roofs)
                        {
                            if (EnsureSetStringInstanceOrType(doc, r, "we_roof_rainwater_strategy", weRoofRain))
                                ensuredRoofWrites++;
                        }
                    }

                    // =====================================================
                    // ✅ FIX B: ss_roof_sri_target driven by ss_heat_island (NO need to depend on API)
                    // =====================================================
                    string sri = ComputeSriTargetFromHeatIsland(rowDict);
                    if (!string.IsNullOrWhiteSpace(sri))
                    {
                        EnsureSetStringInstanceOrType(doc, doc.ProjectInformation, "ss_roof_sri_target", sri);
                        foreach (var v in views)
                            EnsureSetStringInstanceOrType(doc, v, "ss_roof_sri_target", sri);

                        foreach (var r in roofs)
                        {
                            if (EnsureSetStringInstanceOrType(doc, r, "ss_roof_sri_target", sri))
                                ensuredRoofWrites++;
                        }
                    }

                    // =====================================================
                    // ✅ FIX C: ea_wwr_ratio per EXTERIOR wall with hosted windows
                    // =====================================================
                    foreach (var e in walls)
                    {
                        var wall = e as Wall;
                        if (wall == null) continue;
                        if (!IsExteriorWall(wall)) continue;

                        if (!wallWinMap.TryGetValue(wall.Id, out var winsOnWall) || winsOnWall.Count == 0)
                            continue;

                        double wallGrossAreaM2 = TryGetWallGrossAreaM2(wall);
                        if (wallGrossAreaM2 <= 1e-9) continue;

                        double winAreaM2 = 0.0;
                        foreach (var w in winsOnWall)
                            winAreaM2 += TryGetWindowAreaM2(w);

                        if (winAreaM2 <= 1e-9) continue;

                        double ratio = winAreaM2 / wallGrossAreaM2;
                        if (ratio < 0) ratio = 0;
                        if (ratio > 1) ratio = 1;

                        if (EnsureSetDoubleInstanceOrType(doc, wall, "ea_wwr_ratio", ratio))
                            wwrWallWrites++;

                        foreach (var w in winsOnWall)
                        {
                            if (EnsureSetDoubleInstanceOrType(doc, w, "ea_wwr_ratio", ratio))
                                wwrWinWrites++;
                        }
                    }

                    // 7) report to Project Information
                    WriteReportToProjectInformation(doc, REPORT_PARAM_NAME, reportText);

                    tx.Commit();
                }

                // ✅ Export report txt
                string txtOutPath = null;
                if (EXPORT_REPORT_TXT && !string.IsNullOrWhiteSpace(reportOutDir))
                {
                    try
                    {
                        txtOutPath = Path.Combine(
                            reportOutDir,
                            $"LEED_Retrofit_Report_{Path.GetFileNameWithoutExtension(csvPath)}.txt"
                        );
                        File.WriteAllText(txtOutPath, reportText, Encoding.UTF8);
                    }
                    catch
                    {
                        txtOutPath = null;
                    }
                }

                TaskDialog.Show(
                    "CSV + LEED Import Completed",
                    "CSV metrics imported successfully.\n\n" +
                    $"CSV file: {Path.GetFileName(csvPath)}\n" +
                    $"Forced building_id: {(forcedBuildingId ?? "(none)")}\n\n" +
                    $"Roofs found: {roofs.Count}\n" +
                    $"Windows found: {windows.Count}\n" +
                    $"Walls found: {walls.Count}\n" +
                    $"Floors found: {floors.Count}\n" +
                    $"Views found: {views.Count}\n\n" +
                    $"CSV writes → Roofs: {csvRoof}\n" +
                    $"CSV writes → Windows: {csvWindow}\n" +
                    $"CSV writes → Walls: {csvWall}\n" +
                    $"CSV writes → Floors: {csvFloor}\n" +
                    $"CSV writes → ProjectInfo: {csvProj}\n" +
                    $"CSV writes → Views: {csvView}\n\n" +
                    $"API writes → Roofs: {apiRoof}\n" +
                    $"API writes → Windows: {apiWindow}\n" +
                    $"API writes → Walls: {apiWall}\n" +
                    $"API writes → Floors: {apiFloor}\n\n" +
                    $"Text report saved to Project Information parameter:\n  {REPORT_PARAM_NAME}\n\n" +
                    (txtOutPath != null
                        ? $"Text report TXT exported to:\n  {txtOutPath}\n\n"
                        : "Text report TXT export: skipped (no folder selected or write failed).\n\n") +
                    (leedPlan == null ? "LEED Plan: NOT generated.\n\nAI raw:\n" + aiRaw : "LEED Plan: generated by AI (LEED guidance).")
                );

                return Result.Succeeded;
            }
            catch (Exception ex)
            {
                TaskDialog.Show("Import Error", ex.ToString());
                return Result.Failed;
            }
        }

        // =====================================================
        // ✅ building_id by filename
        // =====================================================
        private string GetForcedBuildingIdFromFileName(string csvPath)
        {
            string name = (Path.GetFileNameWithoutExtension(csvPath) ?? "").ToLowerInvariant();

            if (name.Contains("building1") || name.Contains("0001"))
                return "building_0001";
            if (name.Contains("building2") || name.Contains("0002"))
                return "building_0002";

            return null;
        }

        // =====================================================
        // ✅ FIX: read the correct CSV row by building_id
        // =====================================================
        private Dictionary<string, string> ReadMatchingRowAsDict(string path, string forcedBuildingId)
        {
            var lines = File.ReadAllLines(path);
            if (lines.Length < 2) return null;

            char d = lines[0].Contains(";") ? ';' : ',';

            var headerRaw = lines[0].Split(d).ToList();
            var header = headerRaw.Select(NormalizeHeaderName).ToList();

            int idxBuilding = header.FindIndex(h => string.Equals(h, "building_id", StringComparison.OrdinalIgnoreCase));
            Dictionary<string, string> firstNonEmpty = null;

            for (int row = 1; row < lines.Length; row++)
            {
                if (string.IsNullOrWhiteSpace(lines[row])) continue;

                var values = lines[row].Split(d);
                var dict = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);

                bool any = false;
                for (int i = 0; i < header.Count; i++)
                {
                    string key = header[i];
                    if (string.IsNullOrWhiteSpace(key)) continue;

                    string val = i < values.Length ? (values[i] ?? "").Trim() : "";
                    dict[key] = val;
                    if (!string.IsNullOrWhiteSpace(val)) any = true;
                }

                if (!any) continue;
                if (firstNonEmpty == null) firstNonEmpty = dict;

                if (!string.IsNullOrWhiteSpace(forcedBuildingId) && idxBuilding >= 0)
                {
                    if (dict.TryGetValue("building_id", out var bid) &&
                        string.Equals((bid ?? "").Trim(), forcedBuildingId, StringComparison.OrdinalIgnoreCase))
                    {
                        return dict;
                    }
                }
            }

            return firstNonEmpty;
        }

        private string NormalizeHeaderName(string s)
        {
            if (s == null) return "";
            s = s.Trim();

            if (s.Length > 0 && s[0] == '\uFEFF')
                s = s.Substring(1);

            while (s.Contains("  "))
                s = s.Replace("  ", " ");

            return s.Trim();
        }

        // =====================================================
        // ✅ Ensure CSV exact param gets written (instance OR type)
        // =====================================================
        private void EnsureWriteCsvExact(Document doc, Element e, Dictionary<string, string> row, string exactName)
        {
            try
            {
                if (doc == null || e == null || row == null || string.IsNullOrWhiteSpace(exactName)) return;
                if (!row.TryGetValue(exactName, out string raw)) return;
                if (string.IsNullOrWhiteSpace(raw)) return;

                EnsureSetByRawInstanceOrType(doc, e, exactName, raw);
            }
            catch { }
        }

        // =====================================================
        // ✅ Window-only forced CSV write
        // =====================================================
        private int WriteWindowCsvForced(Document doc, Element window, Dictionary<string, string> row)
        {
            if (doc == null || window == null || row == null) return 0;

            if (window.Category == null ||
                window.Category.Id.Value != (int)BuiltInCategory.OST_Windows)
                return 0;

            int c = 0;

            if (row.TryGetValue("ea_window_u_value", out string rawU))
            {
                if (EnsureSetByRawInstanceOrType(doc, window, "ea_window_u_value", rawU))
                    c++;
            }

            return c;
        }

        // =====================================================
        // ✅ WWR helpers (unchanged)
        // =====================================================
        private Dictionary<ElementId, List<FamilyInstance>> BuildWallToWindowsMap(Document doc, List<Element> allWindows)
        {
            var map = new Dictionary<ElementId, List<FamilyInstance>>();

            foreach (var e in allWindows)
            {
                var fi = e as FamilyInstance;
                if (fi == null) continue;

                Element host = null;
                try { host = fi.Host; } catch { host = null; }
                var wall = host as Wall;
                if (wall == null) continue;

                if (!map.TryGetValue(wall.Id, out var list))
                {
                    list = new List<FamilyInstance>();
                    map[wall.Id] = list;
                }
                list.Add(fi);
            }

            return map;
        }

        private bool IsExteriorWall(Wall wall)
        {
            try
            {
                var wt = wall?.WallType;
                if (wt == null) return false;
                return wt.Function == WallFunction.Exterior;
            }
            catch { return false; }
        }

        private double TryGetWallGrossAreaM2(Wall wall)
        {
            try
            {
                var lc = wall.Location as LocationCurve;
                if (lc?.Curve == null) return 0;

                double lenFt = lc.Curve.Length;

                double hFt = 0;
                var ph = wall.get_Parameter(BuiltInParameter.WALL_USER_HEIGHT_PARAM);
                if (ph != null && ph.StorageType == StorageType.Double)
                    hFt = ph.AsDouble();

                if (hFt <= 1e-9)
                {
                    var ph2 = wall.LookupParameter("Unconnected Height") ?? wall.LookupParameter("Nicht verknüpfte Höhe");
                    if (ph2 != null && ph2.StorageType == StorageType.Double)
                        hFt = ph2.AsDouble();
                }

                if (lenFt <= 1e-9 || hFt <= 1e-9) return 0;

                double lenM = UnitUtils.ConvertFromInternalUnits(lenFt, UnitTypeId.Meters);
                double hM = UnitUtils.ConvertFromInternalUnits(hFt, UnitTypeId.Meters);

                return lenM * hM;
            }
            catch { return 0; }
        }

        private double TryGetWindowAreaM2(FamilyInstance fi)
        {
            if (fi == null) return 0.0;

            double best = 0.0;

            try
            {
                double wFt = 0, hFt = 0;
                var pw = fi.get_Parameter(BuiltInParameter.FAMILY_ROUGH_WIDTH_PARAM);
                var ph = fi.get_Parameter(BuiltInParameter.FAMILY_ROUGH_HEIGHT_PARAM);

                if (pw != null && pw.StorageType == StorageType.Double) wFt = pw.AsDouble();
                if (ph != null && ph.StorageType == StorageType.Double) hFt = ph.AsDouble();

                if (wFt > 1e-9 && hFt > 1e-9)
                {
                    double aFt2 = wFt * hFt;
                    double aM2 = UnitUtils.ConvertFromInternalUnits(aFt2, UnitTypeId.SquareMeters);
                    best = Math.Max(best, aM2);
                }
            }
            catch { }

            try
            {
                var p = fi.get_Parameter(BuiltInParameter.HOST_AREA_COMPUTED);
                if (p != null && p.StorageType == StorageType.Double)
                {
                    double internalVal = p.AsDouble();
                    double aM2 = UnitUtils.ConvertFromInternalUnits(internalVal, UnitTypeId.SquareMeters);
                    best = Math.Max(best, aM2);
                }
            }
            catch { }

            return best;
        }

        // =====================================================
        // ✅ ss_roof_sri_target from ss_heat_island
        // =====================================================
        private string ComputeSriTargetFromHeatIsland(Dictionary<string, string> row)
        {
            if (row == null) return "";
            if (!row.TryGetValue("ss_heat_island", out string raw)) return "";
            if (string.IsNullOrWhiteSpace(raw)) return "";

            double v = ParseDouble(raw);
            if (double.IsNaN(v)) return "";

            if (v < 0.33) return "Low";
            if (v <= 0.66) return "Medium";
            return "High";
        }

        // =====================================================
        // ✅ NEW: Revit-derived U-value + orientation helpers
        // =====================================================

        // Try to read U-value from element type using common parameter names (EN/DE)
        private bool TryGetUValueFromElementType(Document doc, Element e, out double uValue)
        {
            uValue = double.NaN;
            if (doc == null || e == null) return false;

            ElementType t = GetElementType(doc, e);
            if (t == null) return false;

            string[] candidates = new[]
            {
        "Wärmedurchgangskoeffizient (U)",
        "Waermedurchgangskoeffizient (U)",
        "Wärmedurchgangskoeffizient",
        "Waermedurchgangskoeffizient",
        "U-Wert",
        "U Wert",
        "U-Value",
        "U Value",
        "Thermal Transmittance"
    };

            foreach (var name in candidates)
            {
                Parameter p = null;
                try { p = t.LookupParameter(name) ?? e.LookupParameter(name); } catch { p = null; }
                if (p == null) continue;

                try
                {
                    // 1) safest: parse displayed value string (often like "0,5400 W/(m²·K)")
                    string vs = "";
                    try { vs = p.AsValueString(); } catch { vs = ""; }

                    if (!string.IsNullOrWhiteSpace(vs))
                    {
                        double v = ParseDouble(StripUnits(vs));
                        if (!double.IsNaN(v) && v >= 0)
                        {
                            uValue = v;
                            return true;
                        }
                    }

                    // 2) fallback: raw double
                    if (p.StorageType == StorageType.Double)
                    {
                        double internalVal = p.AsDouble();
                        if (!double.IsNaN(internalVal) && internalVal >= 0)
                        {
                            uValue = internalVal;
                            return true;
                        }
                    }

                    // 3) fallback: string storage
                    if (p.StorageType == StorageType.String)
                    {
                        string s = (p.AsString() ?? "").Trim();
                        double v = ParseDouble(StripUnits(s));
                        if (!double.IsNaN(v) && v >= 0)
                        {
                            uValue = v;
                            return true;
                        }
                    }
                }
                catch { }
            }

            return false;
        }


        private string StripUnits(string s)
        {
            if (string.IsNullOrWhiteSpace(s)) return "";
            // remove common unit tails like "W/(m²·K)", "W/m²K", etc.
            // keep digits, dot, comma, minus
            var sb = new StringBuilder();
            foreach (char c in s)
            {
                if (char.IsDigit(c) || c == '.' || c == ',' || c == '-' || c == '+')
                    sb.Append(c);
            }
            return sb.ToString();
        }

        // Compute wall azimuth degrees (0..360). 0 = North, 90 = East (approx)
        private bool TryGetWallAzimuthDeg(Wall wall, out double azDeg)
        {
            azDeg = double.NaN;
            if (wall == null) return false;

            try
            {
                var lc = wall.Location as LocationCurve;
                if (lc?.Curve == null) return false;

                XYZ dir = (lc.Curve.GetEndPoint(1) - lc.Curve.GetEndPoint(0));
                if (dir == null) return false;

                dir = new XYZ(dir.X, dir.Y, 0);
                if (dir.GetLength() <= 1e-9) return false;

                dir = dir.Normalize();

                // Angle from North (Y+ assumed North in Revit internal), clockwise
                // North vector = (0,1)
                double angle = Math.Atan2(dir.X, dir.Y); // atan2(East, North)
                double deg = angle * 180.0 / Math.PI;
                if (deg < 0) deg += 360.0;

                azDeg = deg;
                return true;
            }
            catch { return false; }
        }

        // =====================================================
        // ✅ Core "ensure set" helpers: instance OR type
        // =====================================================
        private bool EnsureSetStringInstanceOrType(Document doc, Element e, string exactName, string value)
        {
            if (doc == null || e == null || string.IsNullOrWhiteSpace(exactName)) return false;

            if (TrySetStringExact(e, exactName, value)) return true;

            ElementType t = GetElementType(doc, e);
            if (t != null && TrySetStringExact(t, exactName, value)) return true;

            return false;
        }

        private bool EnsureSetDoubleInstanceOrType(Document doc, Element e, string exactName, double valueMetric)
        {
            if (doc == null || e == null || string.IsNullOrWhiteSpace(exactName)) return false;

            if (TrySetDoubleExact(e, exactName, valueMetric)) return true;

            ElementType t = GetElementType(doc, e);
            if (t != null && TrySetDoubleExact(t, exactName, valueMetric)) return true;

            return false;
        }

        private bool EnsureSetByRawInstanceOrType(Document doc, Element e, string exactName, string raw)
        {
            if (doc == null || e == null || string.IsNullOrWhiteSpace(exactName) || string.IsNullOrWhiteSpace(raw))
                return false;

            if (TrySetByRawExact(doc, e, exactName, raw)) return true;

            ElementType t = GetElementType(doc, e);
            if (t != null && TrySetByRawExact(doc, t, exactName, raw)) return true;

            return false;
        }

        private ElementType GetElementType(Document doc, Element e)
        {
            try
            {
                ElementId tid = e.GetTypeId();
                if (tid == ElementId.InvalidElementId) return null;
                return doc.GetElement(tid) as ElementType;
            }
            catch { return null; }
        }

        private bool TrySetStringExact(Element e, string exactName, string value)
        {
            try
            {
                var p = e.LookupParameter(exactName);
                if (p == null || p.IsReadOnly) return false;

                try
                {
                    if (p.SetValueString(value ?? "")) return true;
                }
                catch { }

                if (p.StorageType == StorageType.String)
                {
                    p.Set(value ?? "");
                    return true;
                }

                return false;
            }
            catch { return false; }
        }

        private bool TrySetDoubleExact(Element e, string exactName, double valueMetric)
        {
            try
            {
                var p = e.LookupParameter(exactName);
                if (p == null || p.IsReadOnly) return false;

                string s = valueMetric.ToString(System.Globalization.CultureInfo.InvariantCulture);

                try
                {
                    if (p.SetValueString(s)) return true;
                }
                catch { }

                if (p.StorageType == StorageType.Double)
                {
                    double internalV = ConvertToInternalIfNeeded(exactName, valueMetric);
                    p.Set(internalV);
                    return true;
                }

                if (p.StorageType == StorageType.String)
                {
                    p.Set(s);
                    return true;
                }

                return false;
            }
            catch { return false; }
        }

        private bool TrySetByRawExact(Document doc, Element e, string exactName, string raw)
        {
            try
            {
                var p = e.LookupParameter(exactName);
                if (p == null || p.IsReadOnly) return false;

                string s = (raw ?? "").Trim();
                if (s.Length >= 2 && s.StartsWith("\"") && s.EndsWith("\""))
                    s = s.Substring(1, s.Length - 2).Trim();
                if (s.EndsWith("\""))
                    s = s.TrimEnd('\"').Trim();
                s = s.Replace(",", ".");

                try
                {
                    if (p.SetValueString(s)) return true;
                }
                catch { }

                if (p.StorageType == StorageType.String)
                {
                    p.Set(s);
                    return true;
                }

                if (p.StorageType == StorageType.Double)
                {
                    double v = ParseDouble(s);
                    double internalV = ConvertToInternalIfNeeded(exactName, v);
                    p.Set(internalV);
                    return true;
                }

                if (p.StorageType == StorageType.Integer)
                {
                    if (bool.TryParse(s, out bool bb))
                    {
                        p.Set(bb ? 1 : 0);
                        return true;
                    }
                    p.Set((int)Math.Round(ParseDouble(s)));
                    return true;
                }

                return false;
            }
            catch { return false; }
        }

        // =====================================================
        // ✅ API → write to specific element categories
        // =====================================================
        private int WriteApiToRoof(Document doc, Element r, LeedPlan p)
        {
            int c = 0;

            if (p?.ea?.targets != null)
            {
                c += Set(doc, r, "ea_pv_panel_count", p.ea.targets.pv_panel_count);
                c += Set(doc, r, "ea_pv_added_area_m2", p.ea.targets.pv_added_area_m2);
                c += Set(doc, r, "ea_pv_layout_status", p.ea.targets.pv_layout_status);
            }

            if (p?.ea?.strategy != null)
            {
                c += Set(doc, r, "ea_roof_pv_strategy", p.ea.strategy.ea_roof_pv_strategy);
                c += Set(doc, r, "ea_roof_pv_system_type", p.ea.strategy.ea_roof_pv_system_type);
                c += Set(doc, r, "ea_roof_structural_capacity_flag", p.ea.strategy.ea_roof_structural_capacity_flag);
            }

            if (p?.ss?.strategies != null)
                c += Set(doc, r, "ss_roof_heat_strategy", p.ss.strategies.ss_roof_heat_strategy);

            if (p?.we?.strategies != null)
                c += Set(doc, r, "we_roof_rainwater_strategy", p.we.strategies.we_roof_rainwater_strategy);

            if (p?.we?.targets != null)
                c += Set(doc, r, "we_rainwater_storage_capacity_m3", p.we.targets.we_rainwater_storage_capacity_m3);

            if (p?.lt?.targets != null)
            {
                c += Set(doc, r, "lt_constraint_flag", p.lt.targets.lt_constraint_flag);
                c += Set(doc, r, "lt_retrofit_intensity_factor", p.lt.targets.lt_retrofit_intensity_factor);
            }

            if (p?.we?.targets != null)
                c += Set(doc, r, "we_water_efficiency_level", p.we.targets.we_water_efficiency_level);

            return c;
        }

        private int WriteApiToWindow(Document doc, Element w, LeedPlan p)
        {
            int c = 0;

            if (p?.ea?.targets != null)
            {
                c += Set(doc, w, "ea_shading_depth_m", p.ea.targets.shading_depth_m);
                c += Set(doc, w, "ea_shading_count", p.ea.targets.shading_count);
                c += Set(doc, w, "ea_shading_status", p.ea.targets.shading_status);
            }

            if (p?.ea?.strategy != null)
            {
                c += Set(doc, w, "ea_window_shading_strategy", p.ea.strategy.ea_window_shading_strategy);
                c += Set(doc, w, "ea_window_upgrade_strategy", p.ea.strategy.ea_window_upgrade_strategy);
            }

            // ✅ NEW: LT fields generated by AI -> write to windows
            if (p?.lt?.targets != null)
            {
                // lt_vlt is a number (0..1). lt_glare_risk_class is enum string: low|medium|high
                c += Set(doc, w, "lt_vlt", p.lt.targets.lt_vlt);
                c += Set(doc, w, "lt_glare_risk_class", p.lt.targets.lt_glare_risk_class);
            }

            return c;
        }

        private int WriteApiToWall(Document doc, Element wa, LeedPlan p)
        {
            int c = 0;
            if (p?.ea?.strategy != null)
                c += Set(doc, wa, "ea_wall_envelope_strategy", p.ea.strategy.ea_wall_envelope_strategy);
            return c;
        }

        private int WriteApiToFloor(Document doc, Element f, LeedPlan p)
        {
            int c = 0;

            if (p?.we?.strategies != null)
                c += Set(doc, f, "we_floor_permeability_strategy", p.we.strategies.we_floor_permeability_strategy);

            if (p?.ea?.strategy != null)
                c += Set(doc, f, "ea_floor_thermal_strategy", p.ea.strategy.ea_floor_thermal_strategy);

            return c;
        }

        private int WriteApiToProjectInfo(Document doc, LeedPlan p)
        {
            int c = 0;
            Element projInfo = doc.ProjectInformation;
            if (projInfo == null || p == null) return 0;

            if (p.lt?.targets != null)
            {
                c += Set(doc, projInfo, "lt_constraint_flag", p.lt.targets.lt_constraint_flag);
                c += Set(doc, projInfo, "lt_retrofit_intensity_factor", p.lt.targets.lt_retrofit_intensity_factor);
            }

            if (p.we?.targets != null)
                c += Set(doc, projInfo, "we_water_efficiency_level", p.we.targets.we_water_efficiency_level);

            return c;
        }

        // =====================================================
        // ✅ CSV → generic write (unchanged)
        // =====================================================
        private int WriteAllCsvParams(Document doc, Element e, Dictionary<string, string> row)
        {
            int count = 0;
            foreach (var kv in row)
            {
                var ps = GetAllParamsInsensitive(doc, e, kv.Key);
                if (ps == null || ps.Count == 0) continue;

                foreach (var p in ps.Where(x => x != null && !x.IsReadOnly))
                {
                    if (SetParamValue(doc, p, kv.Key, kv.Value))
                    {
                        count++;
                        break;
                    }
                }
            }
            return count;
        }

        private int WriteCsvParamsByName(Document doc, Element e, Dictionary<string, string> row, IEnumerable<string> names)
        {
            if (doc == null || e == null || row == null || names == null) return 0;

            int count = 0;
            foreach (var name in names)
            {
                if (!row.TryGetValue(name, out string raw)) continue;

                Parameter p = LookupParamInsensitive(e, name);
                if (p == null || p.IsReadOnly) continue;

                if (SetParamValue(doc, p, name, raw))
                    count++;
            }
            return count;
        }

        private Parameter LookupParamInsensitive(Element e, string name)
        {
            if (e == null || string.IsNullOrWhiteSpace(name)) return null;

            try
            {
                var p0 = e.LookupParameter(name);
                if (p0 != null) return p0;
            }
            catch { }

            try
            {
                foreach (Parameter p in e.Parameters)
                {
                    if (p?.Definition?.Name == null) continue;
                    if (string.Equals(p.Definition.Name, name, StringComparison.OrdinalIgnoreCase))
                        return p;
                }
            }
            catch { }

            return null;
        }

        private List<Parameter> GetAllParamsInsensitive(Document doc, Element e, string name)
        {
            var list = new List<Parameter>();
            if (doc == null || e == null || string.IsNullOrWhiteSpace(name)) return list;

            try
            {
                var p0 = e.LookupParameter(name);
                if (p0 != null) list.Add(p0);
            }
            catch { }

            try
            {
                foreach (Parameter p in e.Parameters)
                {
                    if (p?.Definition?.Name == null) continue;
                    if (string.Equals(p.Definition.Name, name, StringComparison.OrdinalIgnoreCase))
                        list.Add(p);
                }
            }
            catch { }

            try
            {
                ElementId tid = e.GetTypeId();
                if (tid != ElementId.InvalidElementId)
                {
                    var t = doc.GetElement(tid) as ElementType;
                    if (t != null)
                    {
                        var tp0 = t.LookupParameter(name);
                        if (tp0 != null) list.Add(tp0);

                        foreach (Parameter p in t.Parameters)
                        {
                            if (p?.Definition?.Name == null) continue;
                            if (string.Equals(p.Definition.Name, name, StringComparison.OrdinalIgnoreCase))
                                list.Add(p);
                        }
                    }
                }
            }
            catch { }

            return list.Distinct().ToList();
        }

        private bool SetParamValue(Document doc, Parameter p, string paramName, string raw)
        {
            if (p == null) return false;
            if (string.IsNullOrWhiteSpace(raw)) return false;

            raw = raw.Trim();

            try
            {
                switch (p.StorageType)
                {
                    case StorageType.Double:
                        {
                            try
                            {
                                if (p.SetValueString(raw))
                                    return true;
                            }
                            catch { }

                            double v = ParseDouble(raw);
                            double internalV = ConvertToInternalIfNeeded(paramName, v);
                            p.Set(internalV);
                            return true;
                        }

                    case StorageType.Integer:
                        {
                            if (bool.TryParse(raw, out bool bb))
                            {
                                p.Set(bb ? 1 : 0);
                                return true;
                            }

                            p.Set((int)Math.Round(ParseDouble(raw)));
                            return true;
                        }

                    case StorageType.String:
                        {
                            p.Set(raw);
                            return true;
                        }
                }
            }
            catch { }

            return false;
        }

        private int Set(Document doc, Element e, string name, object val)
        {
            if (e == null || string.IsNullOrWhiteSpace(name) || val == null) return 0;

            Parameter p = LookupParamInsensitive(e, name);
            if (p == null || p.IsReadOnly) return 0;

            try
            {
                if (p.StorageType == StorageType.Integer)
                {
                    if (val is bool b)
                    {
                        p.Set(b ? 1 : 0);
                        return 1;
                    }
                    if (val is string sBool && bool.TryParse(sBool.Trim(), out bool bb))
                    {
                        p.Set(bb ? 1 : 0);
                        return 1;
                    }
                    p.Set(Convert.ToInt32(val));
                    return 1;
                }

                if (p.StorageType == StorageType.String)
                {
                    p.Set(val.ToString());
                    return 1;
                }

                if (p.StorageType == StorageType.Double)
                {
                    double v;
                    if (val is string sd) v = ParseDouble(sd);
                    else v = Convert.ToDouble(val);

                    double internalV = ConvertToInternalIfNeeded(name, v);
                    p.Set(internalV);
                    return 1;
                }

                try
                {
                    if (p.SetValueString(val.ToString()))
                        return 1;
                }
                catch { }

                return 0;
            }
            catch { return 0; }
        }

        private double ConvertToInternalIfNeeded(string paramName, double metricValue)
        {
            if (string.IsNullOrWhiteSpace(paramName)) return metricValue;

            string n = paramName.Trim().ToLowerInvariant();

            if (n.EndsWith("_m2"))
                return UnitUtils.ConvertToInternalUnits(metricValue, UnitTypeId.SquareMeters);

            if (n.EndsWith("_m3"))
                return UnitUtils.ConvertToInternalUnits(metricValue, UnitTypeId.CubicMeters);

            if (n.EndsWith("_mm"))
                return UnitUtils.ConvertToInternalUnits(metricValue / 1000.0, UnitTypeId.Meters);

            if (n.EndsWith("_m"))
                return UnitUtils.ConvertToInternalUnits(metricValue, UnitTypeId.Meters);

            // ✅ NEW: degrees -> internal radians (Angle)
            if (n.EndsWith("_deg"))
                return UnitUtils.ConvertToInternalUnits(metricValue, UnitTypeId.Degrees);

            return metricValue;
        }

        private void WriteReportToProjectInformation(Document doc, string paramName, string reportText)
        {
            if (doc == null || string.IsNullOrWhiteSpace(paramName)) return;

            Element projInfo = doc.ProjectInformation;
            if (projInfo == null) return;

            Parameter p = LookupParamInsensitive(projInfo, paramName);
            if (p == null || p.IsReadOnly) return;

            try
            {
                if (p.StorageType == StorageType.String)
                    p.Set(reportText ?? "");
            }
            catch { }
        }

        // =====================================================
        // ✅ DeepSeek LEED plan (UPDATED schema for lt_vlt & lt_glare_risk_class)
        // =====================================================
        private LeedPlan CallDeepSeekLeedPlan(Dictionary<string, string> metrics, out string raw)
        {
            string key = GetApiKey();

            string systemPrompt =
@"You are a LEED building retrofit consultant.
Use the given building metrics to propose retrofit strategies and parameter values.
Return ONLY valid JSON with this structure (no markdown, no extra text):

{
  ""ea"": {
    ""targets"": {
      ""pv_panel_count"": int,
      ""pv_added_area_m2"": number,
      ""pv_layout_status"": string,
      ""shading_depth_m"": number,
      ""shading_count"": int,
      ""shading_status"": string
    },
    ""strategy"": {
      ""ea_roof_pv_strategy"": ""none|limited|full"",
      ""ea_roof_pv_system_type"": ""attached|mounted|bipv"",
      ""ea_roof_structural_capacity_flag"": true|false,
      ""ea_window_shading_strategy"": ""none|fixed|adjustable"",
      ""ea_window_upgrade_strategy"": ""baseline|low_e_double|triple|frame_upgrade"",
      ""ea_wall_envelope_strategy"": ""baseline|insulated_upgrade|high_performance"",
      ""ea_floor_thermal_strategy"": ""baseline|insulated""
    }
  },
  ""ss"": {
    ""strategies"": {
      ""ss_roof_heat_strategy"": ""none|green_roof|cool_roof""
    },
    ""summary"": ""..."",
    ""recommendations"": [""...""]
  },
  ""we"": {
    ""targets"": {
      ""we_rainwater_storage_capacity_m3"": number,
      ""we_water_efficiency_level"": ""low|medium|high""
    },
    ""strategies"": {
      ""we_roof_rainwater_strategy"": ""none|basic|enhanced"",
      ""we_floor_permeability_strategy"": ""impervious|semi_permeable|permeable""
    },
    ""summary"": ""..."",
    ""recommendations"": [""...""]
  },
  ""lt"": {
    ""targets"": {
      ""lt_constraint_flag"": true|false,
      ""lt_retrofit_intensity_factor"": number,
      ""lt_vlt"": number,
      ""lt_glare_risk_class"": ""low|medium|high""
    },
    ""summary"": ""..."",
    ""recommendations"": [""...""]
  },
  ""assumptions"": [""...""]
}

Rules:
- Fill ALL strategy fields with one of the allowed enum values.
- lt_vlt should be between 0 and 1.
- lt_glare_risk_class must be one of: low, medium, high.
- Keep summaries short; recommendations as an engineering checklist.
- If data is missing, put it in assumptions and keep strategy conservative.
- Do NOT include any fields outside this JSON.";

            var sb = new StringBuilder("Building metrics (from CSV selected row):\n");
            foreach (var kv in metrics)
                sb.AppendLine($"- {kv.Key}: {kv.Value}");

            using (var http = new HttpClient())
            {
                http.DefaultRequestHeaders.Authorization =
                    new AuthenticationHeaderValue("Bearer", key);

                var body = new
                {
                    model = DEEPSEEK_MODEL,
                    messages = new[]
                    {
                        new { role = "system", content = systemPrompt },
                        new { role = "user", content = sb.ToString() }
                    },
                    temperature = 0.0
                };

                string json = JsonConvert.SerializeObject(body);
                var resp = http.PostAsync(
                    "https://api.deepseek.com/chat/completions",
                    new StringContent(json, Encoding.UTF8, "application/json")
                ).GetAwaiter().GetResult();

                raw = resp.Content.ReadAsStringAsync().GetAwaiter().GetResult();

                if (!resp.IsSuccessStatusCode)
                    throw new Exception("DeepSeek API error:\n" + raw);

                dynamic root = JsonConvert.DeserializeObject<dynamic>(raw);
                string aiText = root.choices[0].message.content.ToString();

                string jsonOnly = ExtractJsonBlock(aiText);
                if (string.IsNullOrEmpty(jsonOnly))
                    throw new Exception("AI did not return valid JSON.\n\nRaw:\n" + aiText);

                return JsonConvert.DeserializeObject<LeedPlan>(jsonOnly);
            }
        }

        private string ExtractJsonBlock(string text)
        {
            if (string.IsNullOrWhiteSpace(text))
                return null;

            int start = text.IndexOf('{');
            int end = text.LastIndexOf('}');

            if (start < 0 || end <= start)
                return null;

            return text.Substring(start, end - start + 1);
        }

        private string GetApiKey()
        {
            var key = Environment.GetEnvironmentVariable("DEEPSEEK_API_KEY");
            if (string.IsNullOrWhiteSpace(key))
                throw new Exception("Missing environment variable: DEEPSEEK_API_KEY");
            return key.Trim().Replace("\r", "").Replace("\n", "");
        }

        // =====================================================
        // ✅ Build report text
        // =====================================================
        private string BuildHumanReportText(LeedPlan plan, Dictionary<string, string> metrics)
        {
            var sb = new StringBuilder();
            sb.AppendLine("LEED Retrofit Guidance Report");
            sb.AppendLine("========================================");
            sb.AppendLine($"Generated: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
            sb.AppendLine();

            sb.AppendLine("Input Metrics (CSV selected row)");
            sb.AppendLine("----------------------------------------");
            if (metrics != null)
            {
                foreach (var kv in metrics)
                    sb.AppendLine($"{kv.Key}: {kv.Value}");
            }
            sb.AppendLine();

            if (plan == null)
            {
                sb.AppendLine("No plan generated (plan == null).");
                return sb.ToString();
            }

            // ================= EA =================
            sb.AppendLine("EA (Energy & Atmosphere)");
            sb.AppendLine("----------------------------------------");

            if (plan.ea?.strategy != null)
            {
                sb.AppendLine($"ea_roof_pv_strategy: {plan.ea.strategy.ea_roof_pv_strategy}");
                sb.AppendLine($"ea_roof_pv_system_type: {plan.ea.strategy.ea_roof_pv_system_type}");
                sb.AppendLine($"ea_roof_structural_capacity_flag: {plan.ea.strategy.ea_roof_structural_capacity_flag}");
                sb.AppendLine($"ea_window_shading_strategy: {plan.ea.strategy.ea_window_shading_strategy}");
                sb.AppendLine($"ea_window_upgrade_strategy: {plan.ea.strategy.ea_window_upgrade_strategy}");
                sb.AppendLine($"ea_wall_envelope_strategy: {plan.ea.strategy.ea_wall_envelope_strategy}");
                sb.AppendLine($"ea_floor_thermal_strategy: {plan.ea.strategy.ea_floor_thermal_strategy}");
            }
            else
            {
                sb.AppendLine("ea.strategy: (null)");
            }

            if (plan.ea?.targets != null)
            {
                sb.AppendLine($"pv_panel_count: {plan.ea.targets.pv_panel_count}");
                sb.AppendLine($"pv_added_area_m2: {plan.ea.targets.pv_added_area_m2}");
                sb.AppendLine($"pv_layout_status: {plan.ea.targets.pv_layout_status}");
                sb.AppendLine($"shading_depth_m: {plan.ea.targets.shading_depth_m}");
                sb.AppendLine($"shading_count: {plan.ea.targets.shading_count}");
                sb.AppendLine($"shading_status: {plan.ea.targets.shading_status}");
            }
            else
            {
                sb.AppendLine("ea.targets: (null)");
            }
            sb.AppendLine();

            // ================= SS =================
            sb.AppendLine("SS (Sustainable Sites)");
            sb.AppendLine("----------------------------------------");
            if (plan.ss?.strategies != null)
                sb.AppendLine($"ss_roof_heat_strategy: {plan.ss.strategies.ss_roof_heat_strategy}");
            else
                sb.AppendLine("ss.strategies: (null)");

            if (!string.IsNullOrWhiteSpace(plan.ss?.summary))
                sb.AppendLine($"summary: {plan.ss.summary}");

            if (plan.ss?.recommendations != null && plan.ss.recommendations.Count > 0)
            {
                sb.AppendLine("recommendations:");
                foreach (var r in plan.ss.recommendations)
                    sb.AppendLine($"- {r}");
            }
            sb.AppendLine();

            // ================= WE =================
            sb.AppendLine("WE (Water Efficiency)");
            sb.AppendLine("----------------------------------------");
            if (plan.we?.targets != null)
            {
                sb.AppendLine($"we_rainwater_storage_capacity_m3: {plan.we.targets.we_rainwater_storage_capacity_m3}");
                sb.AppendLine($"we_water_efficiency_level: {plan.we.targets.we_water_efficiency_level}");
            }
            else sb.AppendLine("we.targets: (null)");

            if (plan.we?.strategies != null)
            {
                sb.AppendLine($"we_roof_rainwater_strategy: {plan.we.strategies.we_roof_rainwater_strategy}");
                sb.AppendLine($"we_floor_permeability_strategy: {plan.we.strategies.we_floor_permeability_strategy}");
            }
            else sb.AppendLine("we.strategies: (null)");

            if (!string.IsNullOrWhiteSpace(plan.we?.summary))
                sb.AppendLine($"summary: {plan.we.summary}");

            if (plan.we?.recommendations != null && plan.we.recommendations.Count > 0)
            {
                sb.AppendLine("recommendations:");
                foreach (var r in plan.we.recommendations)
                    sb.AppendLine($"- {r}");
            }
            sb.AppendLine();

            // ================= LT =================
            sb.AppendLine("LT (Light / Transit)");
            sb.AppendLine("----------------------------------------");
            if (plan.lt?.targets != null)
            {
                sb.AppendLine($"lt_constraint_flag: {plan.lt.targets.lt_constraint_flag}");
                sb.AppendLine($"lt_retrofit_intensity_factor: {plan.lt.targets.lt_retrofit_intensity_factor}");
                sb.AppendLine($"lt_vlt: {plan.lt.targets.lt_vlt}");
                sb.AppendLine($"lt_glare_risk_class: {plan.lt.targets.lt_glare_risk_class}");
            }
            else sb.AppendLine("lt.targets: (null)");

            if (!string.IsNullOrWhiteSpace(plan.lt?.summary))
                sb.AppendLine($"summary: {plan.lt.summary}");

            if (plan.lt?.recommendations != null && plan.lt.recommendations.Count > 0)
            {
                sb.AppendLine("recommendations:");
                foreach (var r in plan.lt.recommendations)
                    sb.AppendLine($"- {r}");
            }
            sb.AppendLine();

            // ================= assumptions =================
            if (plan.assumptions != null && plan.assumptions.Count > 0)
            {
                sb.AppendLine("Assumptions");
                sb.AppendLine("----------------------------------------");
                foreach (var a in plan.assumptions)
                    sb.AppendLine($"- {a}");
                sb.AppendLine();
            }

            return sb.ToString();
        }


        // =====================================================
        // CSV helpers
        // =====================================================
        private double ParseDouble(string s)
        {
            s = (s ?? "").Trim().Replace(",", ".");
            double.TryParse(
                s,
                System.Globalization.NumberStyles.Any,
                System.Globalization.CultureInfo.InvariantCulture,
                out double v
            );
            return v;
        }

        private string SelectCSVFile()
        {
            var dlg = new Microsoft.Win32.OpenFileDialog
            {
                Filter = "CSV Files (*.csv)|*.csv",
                Title = "Select QGIS CSV Export"
            };
            return dlg.ShowDialog() == true ? dlg.FileName : null;
        }

        private string SelectReportOutputFolder()
        {
            try
            {
                using (var dlg = new System.Windows.Forms.FolderBrowserDialog())
                {
                    dlg.Description = "Select folder to export LEED report TXT";
                    dlg.ShowNewFolderButton = true;
                    var result = dlg.ShowDialog();
                    return result == System.Windows.Forms.DialogResult.OK ? dlg.SelectedPath : null;
                }
            }
            catch { return null; }
        }

        private void ShowTimedPopup(string title, string text, int seconds)
        {
            try
            {
                using (var f = new System.Windows.Forms.Form())
                {
                    f.Text = title;
                    f.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedDialog;
                    f.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
                    f.MaximizeBox = false;
                    f.MinimizeBox = false;
                    f.TopMost = true;
                    f.ShowInTaskbar = false;
                    f.Width = 520;
                    f.Height = 160;

                    var lbl = new System.Windows.Forms.Label();
                    lbl.Text = text;
                    lbl.AutoSize = false;
                    lbl.Dock = System.Windows.Forms.DockStyle.Fill;
                    lbl.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
                    lbl.Font = new System.Drawing.Font("Segoe UI", 10f, System.Drawing.FontStyle.Regular);
                    f.Controls.Add(lbl);

                    var timer = new System.Windows.Forms.Timer();
                    timer.Interval = Math.Max(1, seconds) * 1000;
                    timer.Tick += (s, e) =>
                    {
                        timer.Stop();
                        try { f.Close(); } catch { }
                    };
                    timer.Start();

                    f.ShowDialog();
                }
            }
            catch { }
        }
    }

    // =====================================================
    // ✅ LEED plan data model (UPDATED LT targets)
    // =====================================================
    public class LeedPlan
    {
        public EaSection ea { get; set; }
        public SsSection ss { get; set; }
        public WeSection we { get; set; }
        public LtSection lt { get; set; }
        public List<string> assumptions { get; set; }
    }

    public class EaSection
    {
        public EaTargets targets { get; set; }
        public EaStrategy strategy { get; set; }
    }

    public class EaTargets
    {
        public int pv_panel_count { get; set; }
        public double pv_added_area_m2 { get; set; }
        public string pv_layout_status { get; set; }

        public double shading_depth_m { get; set; }
        public int shading_count { get; set; }
        public string shading_status { get; set; }
    }

    public class EaStrategy
    {
        public string ea_roof_pv_strategy { get; set; }
        public string ea_roof_pv_system_type { get; set; }
        public bool ea_roof_structural_capacity_flag { get; set; }

        public string ea_window_shading_strategy { get; set; }
        public string ea_window_upgrade_strategy { get; set; }

        public string ea_wall_envelope_strategy { get; set; }
        public string ea_floor_thermal_strategy { get; set; }
    }

    public class SsSection
    {
        public SsStrategies strategies { get; set; }
        public string summary { get; set; }
        public List<string> recommendations { get; set; }
    }

    public class SsStrategies
    {
        public string ss_roof_heat_strategy { get; set; }
    }

    public class WeSection
    {
        public WeTargets targets { get; set; }
        public WeStrategies strategies { get; set; }
        public string summary { get; set; }
        public List<string> recommendations { get; set; }
    }

    public class WeTargets
    {
        public double we_rainwater_storage_capacity_m3 { get; set; }
        public string we_water_efficiency_level { get; set; }
    }

    public class WeStrategies
    {
        public string we_roof_rainwater_strategy { get; set; }
        public string we_floor_permeability_strategy { get; set; }
    }

    public class LtSection
    {
        public LtTargets targets { get; set; }
        public string summary { get; set; }
        public List<string> recommendations { get; set; }
    }

    public class LtTargets
    {
        public bool lt_constraint_flag { get; set; }
        public double lt_retrofit_intensity_factor { get; set; }

        // ✅ NEW: AI-generated window daylight metrics
        public double lt_vlt { get; set; }
        public string lt_glare_risk_class { get; set; }
    }
}
